trigger:
  batch: true
  branches:
    include:
      - "master"

workspace:
  clean: all

variables:
  - group: 'BUILD Management Resources'
  - name: buildConfiguration
    value: 'release'
  - name: buildPlatform
    value: 'any cpu'

pool:
  name: 'DAS - Continuous Integration'
  demands: Agent.OS -equals Windows_NT

resources:
  repositories:
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.4.37
    endpoint: "GitHub (SFA)"

steps:
- task: gittools.gittools.setup-gitversion-task.gitversion/setup@0
  displayName: gitversion/setup
  inputs:
    versionSpec: 5.x

- task: gittools.gittools.execute-gitversion-task.gitversion/execute@0
  displayName: gitversion/execute
  inputs:
    useConfigFile: true
    configFilePath: GitVersion.yml

- task: SonarCloudPrepare@1
  displayName: Prepare SonarCloud analysis configuration
  condition: and(succeeded(), or(in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/main'), eq(variables['Build.Reason'], 'PullRequest')))
  inputs:
    SonarCloud: ESFA - SonarCloud
    organization: $(SonarCloudOrganisationKey)
    scannerMode: MSBuild
    projectName: "$(Build.DefinitionName)"
    projectKey: SkillsFundingAgency_das-providerapprenticeshipsservice

- template: azure-pipelines-templates/build/step/dependency-check.yml@das-platform-building-blocks

- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.3.0'
  inputs:
    versionSpec: 4.x

- task: NuGetCommand@2
  displayName: 'NuGet Restore SFA.DAS.ProviderApprenticeshipsService.sln'
  inputs:
    restoreSolution: 'src/SFA.DAS.ProviderApprenticeshipsService.sln'

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore all'
  inputs:
    command: restore
    projects: "src/**/*.csproj"

- task: VSBuild@1
  displayName: 'Build SFA.DAS.ProviderApprenticeshipsService.sln'
  inputs:
    solution: 'src/SFA.DAS.ProviderApprenticeshipsService.sln'
    msbuildArgs: '/m'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    clean: true

- task: VSTest@2
  displayName: 'Run NUnit Tests'
  inputs:
    testAssemblyVer2: |
      **/bin/Release/*UnitTests.dll
      **/bin/Release/*/*UnitTests.dll
      !**/*ClientV2.UnitTests.dll
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: NuGetCommand@2
  displayName: 'NuGet Pack Provider Accounts API Client'
  inputs:
    command: 'pack'
    packagesToPack: 'src/SFA.DAS.PAS.Account.Api.Client/SFA.DAS.PAS.Account.Api.Client.csproj'
    packDestination: '$(Build.ArtifactStagingDirectory)/nuget-publish'
    versioningScheme: byBuildNumber

- task: VSBuild@1
  displayName: 'Publish Provider Accounts API'
  inputs:
    solution: 'src/SFA.DAS.PAS.Account.Api/SFA.DAS.PAS.Account.Api.csproj'
    vsVersion: "15.0"
    msbuildArgs: '/p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:SkipInvalidConfigurations=true /p:publishUrl="$(build.artifactstagingdirectory)/Provider Accounts API"'
    platform: 'anycpu'
    configuration: '$(buildConfiguration)'
    clean: true

- task: ArchiveFiles@2
  displayName: 'Archive Provider Accounts API'
  inputs:
    rootFolderOrFile: '$(build.artifactstagingdirectory)/Provider Accounts API'
    archiveFile: '$(Build.ArtifactStagingDirectory)/Provider Accounts API/SFA.DAS.PAS.Account.Api.zip'

- task: VSBuild@1
  displayName: 'Publish Provider Portal'
  inputs:
    solution: 'src/SFA.DAS.ProviderApprenticeshipsService.Web/SFA.DAS.ProviderApprenticeshipsService.Web.csproj'
    vsVersion: "15.0"
    msbuildArgs: '/p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:SkipInvalidConfigurations=true /p:publishUrl="$(build.artifactstagingdirectory)/Provider Portal"'
    platform: 'anycpu'
    configuration: '$(buildConfiguration)'
    clean: true

- task: ArchiveFiles@2
  displayName: 'Archive Provider Portal'
  inputs:
    rootFolderOrFile: '$(build.artifactstagingdirectory)/Provider Portal'
    archiveFile: '$(Build.ArtifactStagingDirectory)/Provider Portal/SFA.DAS.ProviderApprenticeshipsService.Web.zip'

- task: VSBuild@1
  displayName: 'Publish Provider WebJob'
  inputs:
    solution: 'src/SFA.DAS.PAS.Host.WebJob/SFA.DAS.PAS.Host.WebJob.csproj'
    vsVersion: "15.0"
    msbuildArgs: '/p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:SkipInvalidConfigurations=true /p:publishUrl="$(build.artifactstagingdirectory)/Provider WebJob"'
    platform: 'anycpu'
    configuration: '$(buildConfiguration)'
    clean: true

- task: ArchiveFiles@2
  displayName: 'Archive Provider WebJob'
  inputs:
    rootFolderOrFile: '$(build.artifactstagingdirectory)/Provider WebJob'
    archiveFile: '$(Build.ArtifactStagingDirectory)/Provider WebJob/SFA.DAS.PAS.Host.WebJob.zip'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: |
      src/SFA.DAS.ProviderUrlHelperTests/SFA.DAS.ProviderUrlHelperTests.csproj
      src/SFA.DAS.PAS.Account.Api.ClientV2.UnitTests/SFA.DAS.PAS.Account.Api.ClientV2.UnitTests.csproj
    testRunTitle: dotnet test run

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: |
      src/SFA.DAS.ProviderUrlHelper/SFA.DAS.ProviderUrlHelper.csproj
      src/SFA.DAS.PAS.Account.Api.ClientV2/SFA.DAS.PAS.Account.Api.ClientV2.csproj
      src/SFA.DAS.PAS.Account.Api.Types/SFA.DAS.PAS.Account.Api.Types.csproj
    arguments: '/p:Configuration=$(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    packagesToPack: 'src/SFA.DAS.ProviderUrlHelper/SFA.DAS.ProviderUrlHelper.csproj;src/SFA.DAS.PAS.Account.Api.ClientV2/SFA.DAS.PAS.Account.Api.ClientV2.csproj;src/SFA.DAS.PAS.Account.Api.Types/SFA.DAS.PAS.Account.Api.Types.csproj'
    packDirectory: '$(Build.ArtifactStagingDirectory)/nuget-publish'
    versioningScheme: byBuildNumber
    verbosityPack: Diagnostic

- task: SonarCloudAnalyze@1
  displayName: Run SonarCloud analysis
  condition: and(succeeded(), or(in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/main'), eq(variables['Build.Reason'], 'PullRequest')))

- task: SonarCloudPublish@1
  displayName: Publish SonarCloud analysis results on build summary
  condition: and(succeeded(), or(in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/main'), eq(variables['Build.Reason'], 'PullRequest')))
  inputs:
    pollingTimeoutSec: '300'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    Contents: |
     azure/**
     **/*.dacpac
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Publish'
  inputs:
    ArtifactName: Publish
