trigger:
  batch: true
  branches:
    include:
      - "master"

pool:
  name: 'DAS - Continuous Integration Agents'
  demands: LATEST_DOTNET_VERSION -equals 3.1
  workspace:
    clean: all

variables:
  - name: BuildConfiguration
    value: release
  - name: BuildPlatform
    value: any cpu

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/2.1.0
    endpoint: SkillsFundingAgency

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml
    parameters:
      BuildPlatform: $(BuildPlatform)
      BuildConfiguration: $(BuildConfiguration)
  - template: pipeline-templates/job/dacpac-build.yml