parameters:
  BuildPlatform:
  BuildConfiguration:

jobs:
- job: DACPACBuild
  pool:
    name: DAS - Continuous Integration
    demands: Agent.OS -equals Windows_NT
  workspace:
    clean: all
  steps:
  - task: VSBuild@1
    displayName: Build DACPAC
    inputs:
      solution: src/SFA.DAS.ProviderAgreementStatus.Database/SFA.DAS.ProviderAgreementStatus.Database.sqlproj
      platform: ${{ parameters.BuildPlatform }}
      configuration: ${{ parameters.BuildConfiguration }}
      msbuildArgs: /p:PackageLocation="$(build.artifactstagingdirectory)/publish"

  - task: CopyFiles@2
    displayName: Copy Files to $(build.artifactstagingdirectory)/publish
    inputs:
      Contents: src/**/bin/**/*.dacpac
      TargetFolder: $(build.artifactstagingdirectory)/publish
      OverWrite: true

  - task: PublishPipelineArtifact@1
    displayName: Publish Build Artifact
    inputs:
      targetPath: $(build.artifactstagingdirectory)/publish
      artifactName: dacpac