parameters:
  ServiceConnection:
  SolutionBaseName:
  Environment:
  OverrideBlockOnPossibleDataLoss:
  AppRoleAssignmentsServiceConnection:

jobs:
- deployment: DeployWebApp
  pool:
    name: DAS - Continuous Deployment Agents
  environment: ${{ parameters.Environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - template: azure-pipelines-templates/deploy/step/set-backendaccessrestrictions-variable.yml@das-platform-building-blocks
          parameters:
             ServiceConnection: ${{ parameters.ServiceConnection }}
             SharedEnvResourceGroup: $(SharedEnvResourceGroup)
             SharedEnvVirtualNetworkName: $(SharedEnvVirtualNetworkName)
             BackEndAccessRestrictionsExcludedSubnets: $(BackEndAccessRestrictionsExcludedSubnets)
             ResourceEnvironmentName: $(ResourceEnvironmentName)
             UnrestrictedEnvironments: $(UnrestrictedEnvironments)
             UptimeMonitoringAccessRestrictions: $(UptimeMonitoringAccessRestrictions)
        - template: azure-pipelines-templates/deploy/step/arm-deploy.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            SubscriptionId: $(SubscriptionId)
            Location: $(ResourceGroupLocation)
            Environment: ${{ parameters.Environment }}
            TemplatePath: $(Pipeline.Workspace)/Publish/azure/template.json
            ParametersPath: $(Pipeline.Workspace)/Publish/azure/template.parameters.json
            IsMultiRepoCheckout: true
            TemplateSecrets:
              configurationStorageConnectionString: $(ConfigurationStorageConnectionString)
              loggingRedisConnectionString: $(TLSLoggingRedisConnectionString)
              loggingRedisKey: $(LoggingRedisKey)
              redisSessionProviderConnectionString: $(DefaultSessionRedisConnectionString)
        - template: azure-pipelines-templates/deploy/step/generate-config.yml@das-platform-building-blocks
          parameters:
            EnvironmentName: $(EnvironmentName)
            ServiceConnection: ${{ parameters.ServiceConnection }}
            SourcePath: $(Pipeline.Workspace)/das-employer-config/Configuration/das-providerapprenticeshipservice
            StorageAccountName: $(ConfigurationStorageAccountName)
            StorageAccountResourceGroup: $(SharedEnvResourceGroup)
            TargetFileName: '*.schema.json'
            TableName: Configuration
            ConfigurationSecrets:
              NotificationsClientToken: $(NotificationsClientToken)
              CommitmentNotificationToken: $(CommitmentNotificationToken)
        - template: azure-pipelines-templates/deploy/step/app-role-assignments.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.AppRoleAssignmentsServiceConnection }}
            ResourceName: $(UiAppServiceName)
            Tenant: $(Tenant)
            AADGroupObjectIdArray: $(AdminAADGroupObjectId),$(DevAADGroupObjectId)
            IsMultiRepoCheckout: true
        - template: azure-pipelines-templates/deploy/step/app-deploy.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            AppServiceName: $(UiAppServiceName)
            DeploymentPackagePath: $(Pipeline.Workspace)/Publish/ProviderPortal/SFA.DAS.ProviderApprenticeshipsService.Web.zip
        - template: azure-pipelines-templates/deploy/step/app-deploy.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            AppServiceName: $(ApiAppServiceName)
            DeploymentPackagePath: $(Pipeline.Workspace)/Publish/ProviderAccountsAPI/SFA.DAS.PAS.Account.Api.zip
        - template: azure-pipelines-templates/deploy/step/webjob-deploy.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            AppServiceName: $(WorkerAppServiceName)
            DeploymentPackagePath: $(Pipeline.Workspace)/Publish/ProviderWebJob/SFA.DAS.PAS.Host.WebJob.zip
            DeploymentType: zipDeploy
