parameters:
  ServiceConnection:
  SolutionBaseName:
  Environment:
  OverrideBlockOnPossibleDataLoss:
  AppRoleAssignmentsServiceConnection:

jobs:
- deployment: DeployWebApp
  pool:
    name: DAS - Continuous Deployment Agents
  environment: ${{ parameters.Environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - template: azure-pipelines-templates/deploy/step/set-backendaccessrestrictions-variable.yml@das-platform-building-blocks
          parameters:
             ServiceConnection: ${{ parameters.ServiceConnection }}
             SharedEnvResourceGroup: $(SharedEnvResourceGroup)
             SharedEnvVirtualNetworkName: $(SharedEnvVirtualNetworkName)
             BackEndAccessRestrictionsExcludedSubnets: $(BackEndAccessRestrictionsExcludedSubnets)
             ResourceEnvironmentName: $(ResourceEnvironmentName)
             UnrestrictedEnvironments: $(UnrestrictedEnvironments)
             UptimeMonitoringAccessRestrictions: $(UptimeMonitoringAccessRestrictions)
        - template: azure-pipelines-templates/deploy/step/arm-deploy.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            SubscriptionId: $(SubscriptionId)
            Location: $(ResourceGroupLocation)
            Environment: ${{ parameters.Environment }}
            TemplatePath: $(System.DefaultWorkingDirectory)/das-providerapprenticeshipsservice/Publish/azure/template.json
            ParametersPath: $(System.DefaultWorkingDirectory)/das-providerapprenticeshipsservice/Publish/azure/template.parameters.json
            IsMultiRepoCheckout: true
            TemplateSecrets:
              resourceEnvironmentName: $(ResourceEnvironmentName)
              environmentName: $(EnvironmentName) 
              sharedFrontEndAppServicePlanName: $(SharedFrontEndAppServicePlanName)
              sharedFrontEndSubnetResourceId: $(SharedFrontEndSubnetResourceId)
              sharedBackEndAppServicePlanName: $(SharedBackEndAppServicePlanName)
              sharedBackEndSubnetResourceId: $(SharedBackEndSubnetResourceId)
              sharedEnvResourceGroup: $(SharedEnvResourceGroup)
              sharedEnvVirtualNetworkName: $(SharedEnvVirtualNetworkName)
              workerSubnetObject: $(WorkerSubnetObject)
              subnetServiceEndpointList: $(SubnetServiceEndpointList)
              subnetDelegations: $(SubnetDelegations)
              configurationStorageConnectionString: $(ConfigurationStorageConnectionString)
              loggingRedisConnectionString: $(TLSLoggingRedisConnectionString)
              serviceName: $(ServiceName)
              apiCustomHostname: $(apiCustomHostname)
              apiCertificateName: $(apiCertificateName)
              sharedKeyVaultName: $(SharedKeyVaultName)
              frontEndAccessRestrictions: $(FrontEndAccessRestrictions) 
              backEndAccessRestrictions: $(BackEndAccessRestrictions) 
              workerAccessRestrictions: $(WorkerAccessRestrictions) 
              logLevel: $(LogLevel)
              loggingRedisKey: $(LoggingRedisKey)
              idaAudience: $(idaAudience)
              idaTenant: $(idaTenant)
              uiCustomHostname: $(uiCustomHostname)
              uiCertificateName: $(uiCertificateName)
              redisConnectionType: $(redisConnectionType)
              idamsRealm: $(idamsRealm)
              idamsADFSMetadata: $(idamsADFSMetadata)
              redisSessionProviderConnectionString: $(DefaultSessionRedisConnectionString)
              featureToggle: {"ManageReservations":"$(FeatureToggle_ManageReservations)","ProviderCreateCohortV2":"$(FeatureToggle_ProviderCreateCohortV2)","ProviderManageApprenticesV2":"$(FeatureToggle_ProviderManageApprenticesV2)","ApprenticeDetailsV2":"$(FeatureToggle_ApprenticeDetailsV2)","CohortSummariesV2":"$(FeatureToggle_CohortSummariesV2)","EmployerDemand":"$(FeatureToggle_EmployerDemand)","BulkUploadV2": "$(FeatureToggle_BulkUploadV2)","Traineeships": "$(FeatureToggle_Traineeships)"}
              useStubProviderRelationships: $(UseStubProviderRelationships)
              sharedManagementResourceGroup: $(SharedManagementResourceGroup)
              sharedSQLServerName: $(SharedSQLServerName)
              elasticPoolName: $(elasticPoolName)
              databaseSkuName: $(DatabaseSkuName)
              databaseTier: $(DatabaseTier)
              logAnalyticsWorkspaceName: $(logAnalyticsWorkspaceName)
              resourceGroupLocation: $(ResourceGroupLocation)
              tags: $(Tags)
        - template: azure-pipelines-templates/deploy/step/generate-config.yml@das-platform-building-blocks
          parameters:
            EnvironmentName: $(EnvironmentName)
            ServiceConnection: ${{ parameters.ServiceConnection }}
            SourcePath: $(System.DefaultWorkingDirectory)/das-employer-config/Configuration/das-providerapprenticeshipservice
            StorageAccountName: $(ConfigurationStorageAccountName)
            StorageAccountResourceGroup: $(SharedEnvResourceGroup)
            TargetFileName: '*.schema.json'
            TableName: Configuration
        - template: azure-pipelines-templates/deploy/step/app-role-assignments.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.AppRoleAssignmentsServiceConnection }}
            ResourceName: $(UiAppServiceName)
            Tenant: $(Tenant)
            AADGroupObjectIdArray: $(AdminAADGroupObjectId),$(DevAADGroupObjectId)
            IsMultiRepoCheckout: true
        - template: azure-pipelines-templates/deploy/step/sql-dacpac-deploy.yml@das-platform-building-blocks
          parameters:
            AzureSubscription: ${{ parameters.ServiceConnection }}
            ServerName: $(SharedSQLServerFQDN)
            SqlUsername: $(SharedSQLServerUsername)
            SqlPassword: $(SharedSQLServerPassword)
            DacpacFile:  $(System.DefaultWorkingDirectory)/das-providerapprenticeshipsservice/dacpac/src/SFA.DAS.ProviderAgreementStatus.Database/bin/Release/SFA.DAS.ProviderAgreementStatus.Database.dacpac
            DatabaseName: $(DatabaseName)
            OverrideBlockOnPossibleDataLoss: ${{ parameters.OverrideBlockOnPossibleDataLoss }}
            Environment: ${{ parameters.Environment }}
        - template: azure-pipelines-templates/deploy/step/app-deploy.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            AppServiceName: $(UiAppServiceName)
            DeploymentPackagePath: $(System.DefaultWorkingDirectory)/das-providerapprenticeshipsservice/Publish/ProviderPortal/SFA.DAS.ProviderApprenticeshipsService.Web.zip
        - template: azure-pipelines-templates/deploy/step/app-deploy.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            AppServiceName: $(ApiAppServiceName)
            DeploymentPackagePath: $(System.DefaultWorkingDirectory)/das-providerapprenticeshipsservice/Publish/ProviderAccountsAPI/SFA.DAS.PAS.Account.Api.zip
        - template: azure-pipelines-templates/deploy/step/webjob-deploy.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            AppServiceName: $(WorkerAppServiceName)
            DeploymentPackagePath: $(System.DefaultWorkingDirectory)/das-providerapprenticeshipsservice/Publish/ProviderWebJob/SFA.DAS.PAS.Host.WebJob.zip
            DeploymentType: zipDeploy
