<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <LangVersion>latestmajor</LangVersion>
    <NoWarn>$(NoWarn);CA1873</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.23.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="2.52.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="1.2.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.3.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="2.0.7" OutputItemType="Analyzer" PrivateAssets="all" />
	<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.9" />
	<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="2.1.0" />
	<PackageReference Include="SFA.DAS.Configuration.AzureTableStorage" Version="17.1.165" />
    <PackageReference Include="SFA.DAS.DfESignIn.Auth" Version="17.1.165" />
	<PackageReference Include="OpenTelemetry.Api" Version="1.15.3" />
	<PackageReference Include="Refit" Version="12.1.0" />
	<PackageReference Include="Refit.HttpClientFactory" Version="12.1.0" />
	<PackageReference Include="SFA.DAS.Api.Common" Version="17.1.165" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SFA.DAS.ProviderApprenticeshipsService.Domain\SFA.DAS.ProviderApprenticeshipsService.Domain.csproj" />
    <ProjectReference Include="..\SFA.DAS.ProviderApprenticeshipsService.Infrastructure\SFA.DAS.ProviderApprenticeshipsService.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
